apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch.default.svc.cluster.local:9200
    elasticsearch.requestTimeout: 90000
