apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: {{ .Values.namespace }} 
spec:
  schedule: 1 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: {{ .Values.es.gc.image }}:{{ .Values.es.gc.tag }}
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
