apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Values.namespace }}
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: {{ .Values.busybox.image }}:{{ .Values.busybox.tag }}
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - master
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: es/master
                operator: In
                values:
                - "true"   
      containers:
      - name: es-master
        image: {{ .Values.image }}:{{ .Values.tag }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: {{ .Values.es.env.clusterName }}
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms{{ .Values.es.env.esJavaOps }}m -Xmx{{ .Values.es.env.esJavaOps }}m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: {{ .Values.containers.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.containers.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.containers.livenessProbe.failureThreshold }}
      {{- if .Values.persistence }}
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - name: "storage"
            hostPath:
              path: {{ .Values.volumes.hostPath.path }}
      {{- end -}}
